import enum

class SystemRole(enum.Enum):
    SUPER_ADMIN = "SUPER_ADMIN"
    ADMIN = "ADMIN"
    REGULAR = "REGULAR"

class MusicalRole(enum.Enum):
    FLUTE_PLAYER = "FLUTE_PLAYER"
    CLARINET_PLAYER = "CLARINET_PLAYER"
    SAXOPHONE_PLAYER = "SAXOPHONE_PLAYER"
    TROMBONE_PLAYER = "TROMBONE_PLAYER"
    EUPHONIUM_PLAYER = "EUPHONIUM_PLAYER"
    TUBA_PLAYER = "TUBA_PLAYER"
    FRENCH_HORN_PLAYER = "FRENCH_HORN_PLAYER"
    TRUMPET_PLAYER = "TRUMPET_PLAYER"
    PERCUSSION_PLAYER = "PERCUSSION_PLAYER"

class InstrumentType(enum.Enum):
    PICCOLO = "PICCOLO"
    FLUTE = "FLUTE"
    CLARINET = "CLARINET"
    BASS_CLARINET = "BASS_CLARINET"
    ALTO_SAXOPHONE = "ALTO_SAXOPHONE"
    TENOR_SAXOPHONE = "TENOR_SAXOPHONE"
    BARITONE_SAXOPHONE = "BARITONE_SAXOPHONE"
    SOPRANO_SAXOPHONE = "SOPRANO_SAXOPHONE"
    TROMBONE = "TROMBONE"
    EUPHONIUM = "EUPHONIUM"
    TUBA = "TUBA"
    FRENCH_HORN = "FRENCH_HORN"
    TRUMPET = "TRUMPET"

class InstrumentState(enum.Enum):
    OK = "OK"
    NEEDS_MAINTENANCE = "NEEDS_MAINTENANCE"
    NEEDS_FIXING = "NEEDS_FIXING"
    OUT_OF_SERVICE = "OUT_OF_SERVICE"

class InstrumentReportType(enum.Enum):
    MAINTENANCE = "MAINTENANCE"
    FIX = "FIX"

class InstrumentReportSeverity(enum.Enum):
    SMALL = "SMALL"
    AVERAGE = "AVERAGE"
    BIG = "BIG"

class EventType(enum.Enum):
    REHEARSAL = "REHEARSAL"
    SPECIAL_REHEARSAL = "SPECIAL_REHEARSAL"
    CONCERT = "CONCERT"
    OTHER = "OTHER"

class AttendanceStatus(enum.Enum):
    PRESENT = "PRESENT"
    TARDY = "TARDY"
    ABSENT = "ABSENT"
    JUSTIFIED = "JUSTIFIED"

class RepertoireState(enum.Enum):
    CURRENT = "CURRENT"
    OLD = "OLD"
    FUTURE = "FUTURE"

class NotificationType(enum.Enum):
    EVENT = "EVENT"
    NEWSLETTER = "NEWSLETTER"
    BIRTHDAY = "BIRTHDAY"
    REPORT = "REPORT"
